course1 = {
    "children": [
        {
            "id": 0,
            "title": "Welcome to CS6750: Human-Computer Interaction!",
            "expanded": True,
            "complete": True,
            "children": [
                {"id": 1, 
                 "title": "Video 0.1.1", 
                 "expanded": False, 
                 "complete": True, 
                 "transcript": "Transcript for video 0.1.1. capuchin monkeys are an arboreal species.",
                 "children": []},
                {"id": 2, 
                 "title": "Video 0.1.2", 
                 "expanded": False, 
                 "complete": False, 
                 "transcript": "Transcript for video 0.1.2. the two are kindred spirits.", 
                 "children": []},
            ],
        },
        {
            "id": 3,
            "title": "1.1: Introduction to HCI",
            "expanded": False,
            "complete": True,
            "children": [
                {"id": 4, 
                 "title": "Video 1.1.1", 
                 "expanded": False, 
                 "complete": True, 
                 "transcript": "Transcript for video 1.1.1. kindness is a noun. Kindness is difficult to give to enemies. The world needs more kindness.", 
                 "children": []},
                {"id": 5, 
                 "title": "Video 1.1.2", 
                 "expanded": False, 
                 "complete": True, 
                 "transcript": "Transcript for video 1.1.2. artistic.", 
                 "children": []},
                {"id": 6, 
                 "title": "Video 1.1.3", 
                 "expanded": False, 
                 "complete": False, 
                 "transcript": "Transcript for video 1.1.3. fluvial.", 
                 "children": []},
            ],
        },
    ],
}

course = {
    "id": 0,
    "title": "CS6750: Human-Computer Interaction",
    "expanded": True,
    "icon": "course",
    "children": [
        {
            "id": 100,
            "title": "0.0 Welcome to the course",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 101, "title": "0.0.1 Welcome", "icon": "reading", "expanded": False, "complete": True,  "transcript":"Welcome to CS6750 and thank you for joining the course. This class explores how humans interact with computers through thoughtfully designed interfaces. Throughout the semester we will combine theory, practical examples, and design exercises. You will learn to evaluate existing interfaces and create better ones yourself. By the end of the course you should be able to recognize both effective and ineffective interaction design."},
                {"id": 102, "title": "0.0.2 Accessing the syllabus", "icon": "reflection", "expanded": False, "complete": True,  "transcript":"The syllabus contains the course schedule, grading policy, and important deadlines. It also explains expectations for participation, assignments, and academic integrity. Students should review the syllabus early and refer back to it throughout the semester. Changes to due dates or policies will be communicated through official course announcements. Understanding the syllabus helps avoid confusion later in the course."},
                {"id": 103, "title": "0.0.3 Accessing course content", "icon": "video", "expanded": False, "complete": True,  "transcript":"Course materials are organized into lessons, videos, readings, and assignments. Each lesson builds on concepts introduced earlier in the semester. Videos should be watched in sequence before attempting quizzes or projects. Supplemental resources are available for students who wish to explore topics more deeply. Keeping pace with the weekly content makes later material easier to understand."},
                {"id": 104, "title": "0.0.4 Course structure", "icon": "video", "expanded": False, "complete": True,  "transcript":"The course is divided into modules that each focus on a major HCI topic. Every module contains several short videos followed by activities and assessments. Concepts introduced early provide a foundation for later design methods and evaluation techniques. Assignments encourage students to apply theory to realistic interface problems. The overall structure supports incremental learning across the semester."}
            ]
        },
        {
            "id": 200,
            "title": "1.1 Introduction to HCI",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 201, "title": "1.1.1 Humans", "icon": "reading", "expanded": False, "complete": True,  "transcript":"Humans perceive, remember, and reason differently from computers. Cognitive abilities such as attention and memory influence interface usability. Designers must understand human limitations as well as human strengths. Interfaces that match human expectations reduce errors and frustration. Human-centered design begins with understanding the people who will use a system."},
                {"id": 202, "title": "1.1.2 Computers", "icon": "video", "expanded": False, "complete": True,  "transcript":"Computers process information quickly but require explicit instructions. Software presents information through interfaces that users can understand and manipulate. Hardware capabilities and software constraints both influence interaction design. Designers should understand what computers do well and where users must provide interpretation. Effective systems combine computational power with human judgment."},
                {"id": 203, "title": "1.1.3 Interaction", "icon": "video", "expanded": False, "complete": True,  "transcript":"Interaction is the continuous exchange between a user and a computer system. Every action performed by a user should produce meaningful system feedback. Good interaction minimizes uncertainty and supports users in achieving their goals. Poor interaction creates confusion, hesitation, and unnecessary cognitive effort. Understanding interaction is central to every area of HCI."},
                {"id": 204, "title": "1.1.4 HCI in the big picture", "icon": "video", "expanded": False, "complete": True,  "transcript":"Human-computer interaction combines ideas from computer science, psychology, design, and engineering. Products succeed when technical capability is paired with usable interfaces. HCI contributes to consumer software, healthcare, education, transportation, and many other domains. User experience influences whether technology is adopted or abandoned. The discipline continues to evolve alongside advances in artificial intelligence and ubiquitous computing."},
                {"id": 205, "title": "1.1.5 HCI vs Human Factors", "icon": "video", "expanded": False, "complete": False,  "transcript":"Human factors is a broader discipline concerned with optimizing interactions between people and systems. Human-computer interaction focuses specifically on digital technologies and interactive software. Both fields emphasize safety, efficiency, and user performance. HCI often draws theories and methods from traditional human factors research. Understanding their relationship provides historical context for modern interface design."}
            ]
        },
        {
            "id": 300,
            "title": "2.1 HCI principles",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 301, "title": "2.1.1 Interfaces between users and tasks", "icon": "reading", "expanded": False, "complete": False,  "transcript":"Interfaces exist to help users accomplish meaningful tasks rather than simply operate software. Successful interfaces make task completion feel natural and efficient. Designers should focus on user goals instead of interface mechanics. Every screen, button, and interaction should support a real task. Thinking about tasks leads to more useful interface designs."},
                {"id": 302, "title": "2.1.2 Identifying a task", "icon": "video", "expanded": False, "complete": False,  "transcript":"Task analysis identifies the activities users need to accomplish. Observing real users often reveals differences between assumed and actual workflows. Designers document goals, constraints, and decision points within each task. Accurate task identification improves interface organization and navigation. Good interfaces are grounded in real user behavior rather than designer assumptions."},
                {"id": 303, "title": "2.1.3 Usefulness and usability", "icon": "video", "expanded": False, "complete": False,  "transcript":"Useful systems provide valuable functionality that solves genuine user problems. Usable systems allow people to access that functionality efficiently and comfortably. A product may be useful but difficult to use, or easy to use but not useful. Successful interfaces achieve both usefulness and usability simultaneously. Designers must evaluate each characteristic independently during development."},
                {"id": 304, "title": "2.1.4 HCI principles", "icon": "video", "expanded": False, "complete": False,  "transcript":"HCI principles provide general guidance for creating effective interfaces. Principles such as feedback, consistency, and discoverability appear across many technologies. Designers rely on these principles when evaluating existing interfaces and proposing improvements. Principles are intentionally broad so they apply to diverse interaction contexts. Understanding them provides a foundation for later heuristics and design guidelines."},
                {"id": 305, "title": "2.1.5 Processor view of the user", "icon": "video", "expanded": False, "complete": False,  "transcript":"The processor view models users as information processors who receive, interpret, and respond to stimuli. Memory, attention, and decision making influence interface performance. This perspective supports predictive models of human behavior. Designers use processor models to estimate task difficulty and cognitive load. Although simplified, the processor view remains useful in many design contexts."},
                {"id": 306, "title": "2.1.6 Predictor view of the user", "icon": "video", "expanded": False, "complete": False,  "transcript":"The predictor view attempts to estimate how users will behave before observing them directly. Predictive models help compare interface alternatives early in development. Designers can estimate task times and likely errors using established techniques. Predictions are useful but should eventually be validated with real users. Empirical testing remains an essential part of HCI."},
                {"id": 307, "title": "2.1.7 Participant view of the user", "icon": "video", "expanded": False, "complete": False,  "transcript":"The participant view emphasizes involving users directly throughout the design process. Interviews, usability studies, and co-design sessions provide valuable insights. Users contribute experiences that designers cannot infer from theory alone. Participation helps uncover hidden needs and unexpected workflows. Modern user-centered design strongly embraces this perspective."}
            ]
        },
        {
            "id": 400,
            "title": "2.2 Feedback cycles",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 401, "title": "2.2.1 What is a feedback cycle?", "icon": "reflection", "expanded": False, "complete": False,  "transcript": "A feedback cycle describes the ongoing conversation between a user and a computer system. Users perform actions, observe outcomes, and decide what to do next. Immediate and meaningful feedback reduces uncertainty during interaction. Delayed or ambiguous feedback increases frustration and mistakes. Understanding feedback cycles is essential for designing responsive interfaces."},
                {"id": 402, "title": "2.2.2 Gulf of execution", "icon": "video", "expanded": False, "complete": False, "transcript": "The gulf of execution describes the gap between what users want to accomplish and the actions an interface makes available. A large gulf makes it difficult for users to determine how to begin a task. Clear controls, intuitive labels, and familiar conventions reduce this gap. Designers should help users translate intentions into actions with minimal effort. Narrowing the gulf of execution leads to faster learning and fewer mistakes."},
                {"id": 403, "title": "2.2.3 Gulf of evaluation", "icon": "video", "expanded": False, "complete": False, "transcript": "The gulf of evaluation describes the gap between a system's state and a user's ability to understand it. Interfaces should clearly communicate what has happened after every action. Visual indicators, confirmation messages, and progress feedback help bridge this gulf. When feedback is missing, users often repeat actions or become uncertain about system behavior. Good interface design makes system status continuously visible."},
                {"id": 404, "title": "2.2.4 Norman's feedback cycle stages", "icon": "video", "expanded": False, "complete": False, "transcript": "Norman's model describes interaction as a sequence of forming goals, executing actions, perceiving results, and evaluating outcomes. Each stage presents opportunities for interface design to support the user. Designers should reduce friction at every step of the cycle. Understanding these stages helps explain where usability problems originate. The model remains one of the most influential frameworks in human-computer interaction."}
            ]
        },
        {
            "id": 500,
            "title": "3.1 Intro to Methods",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 501, "title": "3.1.1 User centered design", "icon": "reading", "expanded": False, "complete": False, "transcript": "User-centered design places the needs, goals, and limitations of users at the center of development. Rather than beginning with technology, designers begin by understanding people. User research guides design decisions throughout the entire project. Iterative evaluation ensures that designs continue meeting user needs as they evolve. Successful products almost always involve users throughout development."},
                {"id": 502, "title": "3.1.2 Stakeholders", "icon": "video", "expanded": False, "complete": False, "transcript": "Stakeholders include everyone affected by a system, including users, clients, developers, managers, and support staff. Different stakeholders often have competing priorities and expectations. Designers must balance these perspectives while maintaining usability. Ignoring important stakeholder groups frequently leads to project failure. Identifying stakeholders early improves communication and design outcomes."},
                {"id": 503, "title": "3.1.3 Design lifecycle", "icon": "video", "expanded": False, "complete": False, "transcript": "The design lifecycle describes the repeated process of understanding users, designing solutions, evaluating results, and refining the product. Modern interface development is highly iterative rather than strictly linear. Feedback gathered during evaluation informs the next round of design decisions. Each iteration improves both the interface and the team's understanding of user needs. The lifecycle continues throughout the life of a product."},
                {"id": 504, "title": "3.1.4 Design lifecycle methods", "icon": "video", "expanded": False, "complete": False, "transcript": "Every stage of the design lifecycle employs different research and evaluation methods. Early stages may use interviews, observations, and contextual inquiry to understand users. Later stages often include prototyping, usability testing, surveys, and analytics. Selecting appropriate methods depends on project goals, available resources, and development stage. Effective designers understand both when and why each method should be used."},
                {"id": 505, "title": "3.1.5 AI in the design lifecycle", "icon": "video", "expanded": False, "complete": False, "transcript": "Artificial intelligence is increasingly used throughout the design lifecycle to support research, prototyping, and evaluation. AI tools can summarize user feedback, generate interface concepts, and identify usability issues from large datasets. Designers should treat AI as an assistant rather than a replacement for human judgment. Human oversight remains essential because AI-generated solutions may overlook important user needs or ethical concerns. Effective teams combine AI efficiency with careful human evaluation."},
                {"id": 506, "title": "3.1.6 Design lifecycle vs. feedback cycle", "icon": "video", "expanded": False, "complete": False, "transcript": "The design lifecycle describes how an interface evolves during development, while the feedback cycle describes how users interact with an interface during use. !!!You found Q4!!! One focuses on the work of designers and the other focuses on the experience of users. Understanding both perspectives helps explain why usability problems occur and how they can be addressed. Designers improve products by observing feedback cycles and incorporating those observations into future design iterations. Together these concepts connect design decisions with user behavior."},
                {"id": 507, "title": "3.1.7 Qualitative vs quantitative data", "icon": "video", "expanded": False, "complete": False, "transcript": "Qualitative data explains why users behave as they do, while quantitative data measures how often behaviors occur. Interviews and observations typically produce qualitative insights, whereas surveys and analytics often generate quantitative measurements. Both forms of evidence provide valuable information during interface design. Relying on only one type of data can produce an incomplete understanding of user needs. Successful HCI research often combines both approaches."},
                {"id": 508, "title": "3.1.8 Types of quantitative data", "icon": "video", "expanded": False, "complete": False, "transcript": "Quantitative data includes measurements such as task completion time, error rates, click counts, and satisfaction ratings. These metrics allow designers to compare interface alternatives objectively. Statistical analysis can reveal meaningful differences between competing designs. Careful experimental design is necessary to ensure that measurements are reliable and valid. Quantitative evidence is especially useful when evaluating improvements over time."},
                {"id": 509, "title": "3.1.9 Types of qualitative data", "icon": "video", "expanded": False, "complete": False, "transcript": "Qualitative data captures user experiences, opinions, motivations, and behaviors in rich detail. Interviews, focus groups, diary studies, and observations are common methods for collecting this information. Researchers analyze patterns and themes rather than numerical averages. Qualitative findings often explain unexpected behaviors discovered through quantitative analysis. Together these methods produce a deeper understanding of user experience."}
            ]
        },
        {
            "id": 600,
            "title": "3.2 Research ethics",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 601, "title": "3.2.1 IRB origins", "icon": "reading", "expanded": False, "complete": False, "transcript": "Institutional Review Boards were established to protect people participating in research studies. Historical abuses demonstrated the need for independent ethical oversight of human subjects research. Modern IRBs evaluate research plans before studies begin to ensure participant safety. Researchers must explain potential risks, benefits, and recruitment procedures. Understanding the history of IRBs helps explain the importance of research ethics today."},
                {"id": 602, "title": "3.2.2 Value of research ethics", "icon": "video", "expanded": False, "complete": False, "transcript": "Research ethics protect participants while maintaining public trust in scientific research. Ethical guidelines encourage honesty, transparency, and respect throughout the research process. Participants should never be exposed to unnecessary risks or deception without appropriate justification. Ethical research also improves the credibility and reproducibility of study results. Responsible researchers view ethics as an integral part of good experimental design."},
                {"id": 603, "title": "3.2.3 IRB protocols: human subject interaction", "icon": "video", "expanded": False, "complete": False, "transcript": "Researchers must carefully describe every interaction participants will have during a study. IRBs evaluate whether procedures minimize risk while collecting meaningful data. Study instructions should be clear, respectful, and appropriate for the participant population. Researchers must also explain how privacy and confidentiality will be maintained. Careful planning improves both participant safety and research quality."},
                {"id": 604, "title": "3.2.4 IRB protocols: consent procedures", "icon": "video", "expanded": False, "complete": False, "transcript": "Informed consent ensures that participants understand what a study involves before agreeing to participate. Consent documents explain study goals, procedures, potential risks, and participant rights. Individuals should know that participation is voluntary and that they may withdraw at any time without penalty. Researchers must provide opportunities for participants to ask questions before giving consent. Meaningful informed consent is a cornerstone of ethical human subjects research."},
                {"id": 605, "title": "3.2.5 IRB protocols: wrapping up", "icon": "video", "expanded": False, "complete": False, "transcript": "Researchers should conclude studies by thanking participants and explaining any remaining details about the research. Debriefing is especially important when studies involve incomplete disclosure or deception. Participants should leave with a clear understanding of the study's purpose and outcomes whenever possible. Researchers must also store collected data securely according to approved protocols. Proper study closure demonstrates respect for participants and their contributions."},
                {"id": 606, "title": "3.2.6 Research ethics and industry", "icon": "video", "expanded": False, "complete": False, "transcript": "Ethical considerations extend beyond universities into commercial technology companies and product development. Businesses regularly collect user data to improve products and personalize experiences. Organizations must balance innovation with privacy, transparency, and user autonomy. Poor ethical decisions can damage public trust and create legal consequences. Ethical thinking should remain part of every stage of product development."},
                {"id": 607, "title": "3.2.7 Facebook emotional manipulation experiment", "icon": "video", "expanded": False, "complete": False, "transcript": "The Facebook emotional contagion experiment became a widely discussed example of ethical concerns in large-scale online research. !!!You found Q3!!!  Researchers modified the emotional content shown in users' news feeds to study behavioral effects. Although the study produced interesting scientific findings, many people questioned whether users had provided meaningful informed consent. The controversy highlighted tensions between innovation, user privacy, and research ethics. The case continues to influence discussions about ethical experimentation on digital platforms."}
            ]
        },
        {
            "id": 700,
            "title": "2.3 Direct manipulation (has code1)",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 701, "title": "2.3.1 Direct manipulation", "icon": "reading", "expanded": False, "complete": False, "transcript": "Direct manipulation allows users to interact with visible objects rather than issuing abstract commands. Dragging files, resizing windows, and drawing on a canvas are common examples of direct manipulation. Immediate feedback helps users understand the effects of every action they perform. Interfaces based on direct manipulation often feel intuitive because they mirror interactions in the physical world. This design philosophy has influenced graphical user interfaces for decades."},
                {"id": 702, "title": "2.3.2 Working task vs working interface", "icon": "video", "expanded": False, "complete": False, "transcript": "Users want to accomplish meaningful tasks rather than learn the mechanics of an interface. Good interfaces keep attention focused on the task instead of the controls themselves. Poor interfaces force users to think about menus, commands, and navigation instead of their actual goals. Designers should minimize unnecessary interaction costs whenever possible. Successful products allow the interface to fade into the background."},
                {"id": 703, "title": "2.3.3 Invisible interfaces", "icon": "video", "expanded": False, "complete": False, "transcript": "An invisible interface is one that requires little conscious attention from its users. Familiar controls and predictable behavior reduce the need for deliberate thought during interaction. Users should spend their effort completing work rather than figuring out the interface. Invisible interfaces often result from careful refinement rather than visual simplicity alone. The goal is not to remove the interface but to make it feel effortless."},
                {"id": 704, "title": "2.3.4 Invisibility by design", "icon": "video", "expanded": False, "complete": False, "transcript": "Interfaces become invisible through thoughtful design decisions that match user expectations. Consistent layouts, recognizable controls, and meaningful feedback reduce cognitive effort. Designers intentionally remove unnecessary complexity while preserving essential functionality. Small improvements accumulate to create interactions that feel natural. Careful design makes technology appear easier to use than it actually is."},
                {"id": 705, "title": "2.3.5 Invisibility by practice", "icon": "video", "expanded": False, "complete": False, "transcript": "Users also experience invisibility through repeated practice and growing familiarity with an interface. Frequent interaction builds habits that reduce cognitive workload over time. Expert users often perform complex tasks with little conscious effort because their actions become automatic. Designers should support both beginners and experienced users without sacrificing usability. Learning and interface design work together to create fluent interaction."},
                {"id": 706, "title": "2.3.6 Code1", "icon": "video", "expanded": False, "complete": False, "transcript": "Several practical guidelines help designers create interfaces that feel natural and efficient. Keep frequently used actions visible, provide immediate feedback, minimize unnecessary steps, use familiar conventions, and maintain consistency throughout the interface. These recommendations reduce user frustration while improving performance. Simple design decisions often have a larger impact than complex features. Applying these tips consistently leads to better user experiences."}
            ]
        },
        {
            "id": 800,
            "title": "2.5 Principles and heuristics",
            "expanded": False,
            "icon": "lesson",
            "children": [
                {"id": 801, "title": "2.5.1 Discoverability", "icon": "reading", "expanded": False, "complete": False, "transcript": "Discoverability refers to how easily users can find available actions within an interface. Visible controls, meaningful labels, and clear organization improve discoverability. Hidden functionality often causes users to overlook useful features. Designers should avoid making important actions difficult to locate. Improving discoverability reduces confusion and shortens the learning process."},
                {"id": 802, "title": "2.5.2 Simplicity", "icon": "video", "expanded": False, "complete": False, "transcript": "Simplicity reduces unnecessary complexity while preserving essential functionality. Simple interfaces are easier to learn, easier to remember, and less likely to overwhelm users. Simplicity does not mean removing useful features but organizing them thoughtfully. Every element on the screen should serve a clear purpose. Good design removes clutter without sacrificing capability."},
                {"id": 803, "title": "2.5.3 Affordances", "icon": "video", "expanded": False, "complete": False, "transcript": "Affordances describe the actions that users perceive an object allows them to perform. Buttons appear pressable, sliders appear draggable, and links appear clickable because of their visual design. Strong affordances reduce the need for written instructions. Designers use shape, color, and motion to communicate possible interactions. Effective affordances help users act confidently without hesitation."},
                {"id": 804, "title": "2.5.4 Mapping", "icon": "video", "expanded": False, "complete": False, "transcript": "Mapping describes the relationship between controls and their effects within a system. Natural mapping allows users to predict outcomes without additional explanation. Stove controls arranged to match burner positions are a classic example of good mapping. Poor mapping forces users to memorize arbitrary relationships. Designers should create interfaces whose behavior matches user expectations."},
                {"id": 805, "title": "2.5.5 Perceptibility", "icon": "video", "expanded": False, "complete": False, "transcript": "Perceptibility ensures that important information is easy to see, hear, or otherwise recognize. Good contrast, readable typography, and meaningful icons improve perceptibility. Users cannot interact effectively with information they fail to notice. Accessibility considerations often improve perceptibility for everyone. Interfaces should communicate critical information clearly under a wide range of conditions."},
                {"id": 806, "title": "2.5.6 Consistency", "icon": "video", "expanded": False, "complete": False, "transcript": "Consistency allows users to transfer knowledge from one part of an interface to another. Similar controls should behave similarly throughout a product. Consistent terminology, layouts, and interaction patterns reduce learning time and errors. Inconsistent behavior creates uncertainty and slows task completion. Maintaining consistency is one of the most widely recognized principles of interface design."},
                {"id": 807, "title": "2.5.7 Flexibility", "icon": "reflection", "expanded": False, "complete": False, "transcript": "Flexible interfaces accommodate users with Code2 different experience levels, preferences, and workflows. Keyboard shortcuts, customization options, and multiple input methods improve flexibility. Beginners may rely on menus while experts prefer accelerators. Supporting multiple interaction styles increases efficiency for a broader audience. Flexibility should enhance usability without increasing unnecessary complexity."},
                {"id": 808, "title": "2.5.8 Equity", "icon": "video", "expanded": False, "complete": False, "transcript": "Equitable design seeks to create interfaces that are usable by people with diverse abilities, backgrounds, and circumstances. Accessibility features should be integrated rather than treated as optional additions. Inclusive design benefits all users by reducing unnecessary barriers. Designers should consider a wide variety of users throughout the development process. Equity strengthens both usability and social responsibility."},
                {"id": 809, "title": "2.5.9 Ease and comfort", "icon": "video", "expanded": False, "complete": False, "transcript": "Comfortable interfaces minimize physical effort and mental workload during interaction. Clear layouts, efficient workflows, and readable content reduce user fatigue. Small improvements in comfort become significant during frequent or prolonged use. Designers should consider ergonomics alongside visual aesthetics. Interfaces that feel comfortable encourage sustained engagement."},
                {"id": 810, "title": "2.5.10 Structure", "icon": "video", "expanded": False, "complete": False, "transcript": "Structure organizes information into logical groups that users can easily understand. Clear hierarchies, headings, and navigation systems help users locate information efficiently. Well-structured interfaces reduce cognitive load by presenting information predictably. Organization should reflect users' mental models whenever possible. Strong information architecture supports both learning and efficient task completion."},
                {"id": 811, "title": "2.5.11 Constraints", "icon": "video", "expanded": False, "complete": False, "transcript": "Constraints limit available actions in order to prevent mistakes and guide users toward successful outcomes. Disabled controls, input validation, and restricted choices are common examples of interface constraints. Appropriate constraints simplify decision making by eliminating invalid options. Poorly designed constraints may frustrate experienced users if they become overly restrictive. Effective constraints balance freedom with error prevention."},
                {"id": 812, "title": "2.5.12 Error tolerance", "icon": "video", "expanded": False, "complete": False, "transcript": "Error tolerance helps users recover gracefully when mistakes occur during interaction. Confirmation dialogs, undo functionality, and informative error messages reduce the consequences of errors. Interfaces should anticipate common mistakes rather than simply reporting failures. Users gain confidence when they know errors are reversible. Designing for recovery is as important as designing for prevention."},
                {"id": 813, "title": "2.5.13 Feedback", "icon": "video", "expanded": False, "complete": False, "transcript": "Feedback communicates the results of user actions quickly and clearly. Progress indicators, animations, sounds, and confirmation messages reassure users that the system is responding. Without feedback users may become uncertain or repeat actions unnecessarily. Effective feedback reduces the gulf of evaluation and supports confident interaction. Immediate feedback is a hallmark of usable interfaces."},
                {"id": 814, "title": "2.5.14 Documentation", "icon": "video", "expanded": False, "complete": False, "transcript": "Documentation provides guidance when users need additional help understanding an interface. Good documentation is searchable, concise, and integrated naturally into the product. Tooltips, tutorials, and contextual help reduce the need to leave the current task. Documentation should supplement intuitive design rather than compensate for poor usability. Effective help systems support both novice and experienced users."},
                {"id": 815, "title": "2.5.15 Other sets of principles", "icon": "video", "expanded": False, "complete": False, "transcript": "Many organizations and researchers have proposed their own collections of usability principles and design heuristics. Although the wording differs, most emphasize consistency, feedback, visibility, simplicity, and user control. Comparing different frameworks reveals common themes across decades of HCI research. Designers benefit from understanding multiple perspectives rather than memorizing a single list. Principles provide guidance rather than rigid rules."},
                {"id": 816, "title": "2.5.16 AI and design principles", "icon": "video", "expanded": False, "complete": False, "transcript": "Artificial intelligence introduces new challenges for traditional interface design principles. AI systems should communicate uncertainty, explain recommendations, and maintain appropriate user control. Transparency and trust become especially important when algorithms influence decisions. Designers must balance powerful automation with meaningful human oversight. Applying established HCI principles helps create AI systems that remain understandable, predictable, and responsible."}
            ]
        }
    ]
}